### ISSUE TITLE
New Hosting Donor?

### ISSUE THREAD

**Issue by mro** [piccolo2d/piccolo2d.github.io#7]
Hi all,

another decade went by and I will end donating the piccolo2d.org domain with next October (2023).

Who steps up to maintain the domain onwards?

If nobody steps up, I will (around April 2023)

* remove the current DNS records for `piccolo2d.org` pointing to `piccolo2d.github.io`
* change the html content to refer to `piccolo2d.github.io` where appropriate

and finally transfer the domain to [Mr. Naohiro Arita](https://github.com/piccolo2d/piccolo2d.github.io/issues/4#issuecomment-146969486) if he wants so (around September 1st 2023).

**Comment by mro** [comment]
will do the DNS and content change on Thu, April 13th.

**Comment by mro** [comment]
Taking you guys @heuermh @steveonjava, @bederson in the loop.

**Comment by bederson** [comment]
I so appreciate what all of you done with Piccolo2D - and I totally understand moving on. I think Piccolo2D was amazing for its time, think that the way you and the broader community ran with it was a perfect example of open source working well. But given the reality that there are other better solutions out there now, and the fact that the repository can stay but without the domain, I think it is time to let this go.

FWIW, I maintain my old academic Piccolo page at http://www.cs.umd.edu/hcil/piccolo/index.shtml, and will change the link from there to github as well unless I hear otherwise.

**Comment by mro** [comment]
thanks @bederson and thanks for keeping the old home stable. I let things sit until April 13th and then update the links as said. Hosting is payed until October. I will set up redirects piccolo2d.org -> github.io and nudge the internet archive to archive those before piccolo2d.org expires.

**Comment by heuermh** [comment]
Thank you, @mro!  Along with the website changes, it wouldn't take too much to repackage under `io.github.piccolo2d` or `com.github.piccolo2d` groupIds, I will volunteer to do so.

@bederson curious which better solutions are out there now 😉   I haven't found anything since with a nice screengraph implementation and good extensibility.

**Comment by bederson** [comment]
Ha! Fair enough @heuermh - even as I wrote that, I was thinking I should have written more commonly used than actually better :) But SVG and HTML Canvas and any number of libraries seems to get a lot of people far enough...

**Comment by mro** [comment]
> repackage under `io.github.piccolo2d` or `com.github.piccolo2d` groupIds

I would hesitate to do so as the github domains are under 3rd party control. I would even rather stick with a 'wrong' legacy domain (in terms of java naming) than moving to microsoft. If changing, maybe even to the old umd. Personally I would leave things as is, however.

But I have no strong feelings, so do as you find appropriate.
